; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --force-update
; RUN: llc -verify-machineinstrs -mtriple=aarch64-- -O1 -fast-isel=0 -global-isel=false %s -o - | FileCheck %s -check-prefix=NOLSE
; RUN: llc -verify-machineinstrs -mtriple=aarch64-- -mattr=+lse -O1 -fast-isel=0 -global-isel=false %s -o - | FileCheck %s -check-prefix=LSE

define i8* @test_rmw_xchg_pointer(i8** %dst, i8* %new) {
; NOLSE-LABEL: test_rmw_xchg_pointer:
; NOLSE:       // %bb.0:
; NOLSE-NEXT:    mov x8, x0
; NOLSE-NEXT:  .LBB0_1: // %atomicrmw.start
; NOLSE-NEXT:    // =>This Inner Loop Header: Depth=1
; NOLSE-NEXT:    ldaxr x0, [x8]
; NOLSE-NEXT:    stlxr w9, x1, [x8]
; NOLSE-NEXT:    cbnz w9, .LBB0_1
; NOLSE-NEXT:  // %bb.2: // %atomicrmw.end
; NOLSE-NEXT:    ret
;
; LSE-LABEL: test_rmw_xchg_pointer:
; LSE:       // %bb.0:
; LSE-NEXT:    swpal x1, x0, [x0]
; LSE-NEXT:    ret
  %res = atomicrmw xchg i8** %dst, i8* %new seq_cst
  ret i8* %res
}
